name: 🔂 Surge PR Preview

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Postgres client with custom settings
        # You may pin to the exact commit or the version.
        # uses: Oxfos/action-postgres-setup@be65c9b48a454ca92582a216197ba4b8b8f5433b
        uses: Oxfos/action-postgres-setup@v1
        with:
          # postgres_user
          POSTGRES_USER: postgres
          # postgres_password
          POSTGRES_PASSWORD: postgres
          # postgres_db
          POSTGRES_DB: postgres
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
